### ISSUE TITLE
PDF document does NOT display by upgraded pdfjs-dist to the latest version 2.7.570

### ISSUE THREAD

**Issue by tanshuai** [sandanat/vue-pdf-app#47]
I failed to upgrade pdfjs-dist to the latest version to use new features.

#### Configuration:
- Web browser and it`s version: Google Chrome, Version 90.0.4430.93 (Official Build) (x86_64)
- Operating system and it`s version: macOS Catalina, Version 10.15.7 (19H524)
- vue-pdf-app version: 2.0.0

#### Steps to reproduce the problem:

1. Download the latest stable release of pdfjs-dist from: https://registry.npmjs.org/pdfjs-dist/-/pdfjs-dist-2.7.570.tgz
2. Extract and replace to  ./vue-pdf-app/src/pdfjs-dist 
3. Run ```npm install``` 
4. Run ```npm run serve```
5. Open browser to http://localhost:8080/ 

#### What is the expected behavior?

Display PDF Document.

#### What went wrong?

```
Uncaught (in promise) TypeError: Cannot set property 'textContent' of undefined
    at PDFLayerViewer.reset (base_tree_viewer.js?a06b:49)
    at PDFLayerViewer.reset (pdf_layer_viewer.js?7ac2:42)
    at new BaseTreeViewer (base_tree_viewer.js?a06b:42)
    at PDFLayerViewer._createSuperInternal (createSuper.js?2d0d:15)
    at new PDFLayerViewer (pdf_layer_viewer.js?7ac2:33)
    at _callee6$ (app.js?ead8:456)
    at tryCatch (pdf.js?8750:34)
    at Generator.invoke [as _invoke] (pdf.js?8750:34)
    at Generator.eval [as next] (pdf.js?8750:34)
    at asyncGeneratorStep (asyncToGenerator.js?c973:3)
```

#### Attachments (screenshots, links, etc)

![image](https://user-images.githubusercontent.com/3947852/117133644-195c8600-add7-11eb-8e1d-f764e8df54b4.png)

Thanks!

**Comment by sandanat** [comment]
Hi!
Unfortunately it is impossible just to replace `src/pdfjs-dist` with the new version of pdfjs. I had to edit source code of pdfjs to make it work with SPA (otherwise Pdfjs would be included as a dependensy in a package.json).

I also don't have plans to update pdfjs-dist because as mentioned in [v2.7 release notes](https://github.com/mozilla/pdf.js/releases) Mozilla has dropped support for IE11.

New version of pdfjs will be included in a package for Vue 3 this summer.
